# Generated by Django 2.2.7 on 2019-12-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_app', '0003_auto_20191219_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='isusing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
