# Generated by Django 2.2.7 on 2019-12-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_app', '0005_auto_20191219_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='isusing',
            new_name='is_using',
        ),
        migrations.AddField(
            model_name='characters',
            name='number_of_role',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
