# Generated by Django 2.2.7 on 2019-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_app', '0006_auto_20191219_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characters',
            old_name='number_of_role',
            new_name='number_of_players',
        ),
    ]
