# Generated by Django 2.2.7 on 2019-12-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_app', '0009_testplayer_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplayer',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
