# Generated by Django 2.2.7 on 2019-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_club_app', '0010_auto_20191219_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalon_Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('is_using', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Werewolf_Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
                ('is_using', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='TestPlayer',
            new_name='Players',
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
    ]
